version: '3.3'

services:
  mysql_db_aws:
    image: mysql:8.0.30
    environment:
      - ENV=docker-prod
    env_file:
      - ".env-docker-prod"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - my-db-prod:/var/lib/mysql


  api:
    build: .
    volumes:
      - .:/code
    depends_on:
      - mysql_db_aws
    ports:
      - "5500:5500"
    environment:
      - ENV=docker-prod
    command:
      [
        "uvicorn",
        "yelloow.api.main:app",
        "--host",
        "0.0.0.0",
        "--ws-ping-interval",
        "5",
        "--ws-ping-timeout",
        "5",
        "--port",
        "5500",
        "--reload",
        "--use-colors"
      ]
    env_file:
      - ".env-docker-dev"

volumes:
  code-volume-prod:
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
  my-db-prod: