version: '3.3'

services:
  # mysql_db:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.db
  #   env_file:
  #     - ".env-docker-dev"
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - '3306:3306'
  #   volumes:
  #     - my-db:/var/lib/mysql
  mysql_db:
    image: mysql:8.0.30
    environment:
      - ENV=docker-dev
    env_file:
      - ".env-docker-dev"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql

  app:
    build: .
    volumes:
      - code-volume:/code
    depends_on: 
      - mysql_db
    command: ["python", "src/yelloow_app/app/yelloow_app.py"]
    
  # api:
  #   build: .
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - mysql_db
  #   ports:
  #     - "5500:5500"
  #   command:
  #     [
  #       "uvicorn"
  #       "yelloow.api.main:app",
  #       "--host",
  #       "0.0.0.0",
  #       "--ws-ping-interval",
  #       "5",
  #       "--ws-ping-timeout",
  #       "5",
  #       "--port",
  #       "5500",
  #       "--reload",
  #       "--use-colors"
  #     ]
  #   env_file:
  #     - ".env-docker-dev"

volumes:
  code-volume:
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
  my-db: